title: ShowChat
sass:
  sass_dir: css
  style:    compressed

# The credits show up in the includes/_footer.html
credits: '<p>Creat cu &hearts; de catre <a href="https://baiatrau.showchat.tk/">BaiatRau</a> bazat pe <a href="https://jekyllrb.com/" target="_blank">Jekyll</a></p>'

# Main author of the website
# See > authors.yml
author: Show-Chat

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://m.showchat.tk'
baseurl: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://m.showchat.tk/img/'

# Chat Image
chatimg: 'https://m.showchat.tk/assets/chat/'

#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#

socialmedia:
    twitter: showchat
    facebook: showchat
    
 
#     ___              _     __           __
#    /   |  __________(_)___/ /___  _____/ /_____  _____
#   / /| | / ___/ ___/ / __  / __ \/ ___/ __/ __ \/ ___/
#  / ___ |(__  ) /__/ / /_/ / /_/ / /__/ /_/ /_/ / /
# /_/  |_/____/\___/_/\__,_/\____/\___/\__/\____/_/
#
#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor
#
#

asciidoctor-enabled: false
asciidoctor:
  description: 
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font   
    
